"""
DataLogger — TensorBoard + W&B logging facade.

Generated by nautilus /add-data-logger skill.
Active features: both backend(s); features: image,scalar,text

Usage:
    from data_logger import DataLogger
    dl = DataLogger(log_dir="./logs", project="my-project", run_name="exp1")
    dl.record("loss", 0.42, step=0)
    dl.record_dict({"acc": 0.9, "lr": 1e-3}, step=0)
    dl.record("frame", img_array_HWC, step=0, data_type="image")
    dl.log_text("note", "epoch 0 complete", step=0)
    dl.close()

Dependencies:
    pip install tensorboardX
    pip install wandb
    pip install numpy
"""
from __future__ import annotations

import os
import time
from typing import Any, Mapping, Optional

import numpy as np


class DataLogger:
    """
    Unified logging facade. Backends are independent — disabling all of them
    leaves record() as a no-op except for the running-stats cache.
    """

    def __init__(
        self,
        log_dir: str,
        log_tb: bool = True,
        log_wandb: bool = False,
        project: Optional[str] = None,
        run_name: Optional[str] = None,
        entity: Optional[str] = None,
        config: Optional[dict] = None,
        wandb_init_retries: int = 10,
        wandb_init_backoff_seconds: float = 30.0,
    ):
        os.makedirs(log_dir, exist_ok=True)
        self._tb_logger = None
        self._wandb_logger = None
        self._data: dict[str, list[float]] = {}

        if log_tb:
            from tensorboardX import SummaryWriter
            self._tb_logger = SummaryWriter(os.path.join(log_dir, "tb"))

        if log_wandb:
            self._init_wandb(
                log_dir=log_dir,
                project=project,
                run_name=run_name,
                entity=entity,
                config=config,
                retries=wandb_init_retries,
                backoff=wandb_init_backoff_seconds,
            )

    def _init_wandb(
        self,
        log_dir: str,
        project: Optional[str],
        run_name: Optional[str],
        entity: Optional[str],
        config: Optional[dict],
        retries: int,
        backoff: float,
    ) -> None:
        import wandb
        for attempt in range(retries):
            try:
                self._wandb_logger = wandb
                self._wandb_logger.init(
                    entity=entity,
                    project=project,
                    name=run_name,
                    dir=log_dir,
                    config=config,
                    mode=("offline" if attempt == retries - 1 else "online"),
                )
                break
            except Exception as e:
                print("[DataLogger] wandb init attempt #{} failed: {}".format(attempt + 1, e))
                self._wandb_logger = None
                time.sleep(backoff)

    # ---------- record API ----------

    def record(
        self,
        k: str,
        v: Any,
        step: int,
        data_type: str = "scalar",
        log_stats: bool = False,
    ) -> None:
        """
        Args:
            k: metric key.
            v: scalar float, or HxWxC / NxHxWxC ndarray for images.
            step: global step / iteration.
            data_type: "scalar" | "image".
            log_stats: scalar-only — also write running mean/std/min/max.
        """
        valid_types = ("scalar", "image",)
        assert data_type in valid_types, "unknown data_type: {}".format(data_type)

        if data_type == "scalar":
            self._cache_if_needed(k, v, log_stats)
            self._log_scalar(k, v, step)
            if log_stats:
                self._log_stats(k, step)
        elif data_type == "image":
            self._log_image(k, v, step)

    def record_dict(
        self,
        metrics: Mapping[str, Any],
        step: int,
        data_type: str = "scalar",
        log_stats: bool = False,
    ) -> None:
        """Batch-record many keys at the same step."""
        for k, v in metrics.items():
            self.record(k, v, step=step, data_type=data_type, log_stats=log_stats)

    def log_text(self, k: str, msg: str, step: int) -> None:
        """Log a text annotation (release notes, eval breakdown, command line, etc.)."""
        if self._tb_logger is not None:
            self._tb_logger.add_text(k, msg, global_step=step)
        if self._wandb_logger is not None:
            try:
                self._wandb_logger.log({k: msg}, step=step)
            except Exception as e:
                print("[DataLogger] wandb text log: {}".format(e))

    # ---------- private writers ----------

    def _cache_if_needed(self, k: str, v: float, log_stats: bool) -> None:
        # Once a key is requested with stats, keep accumulating it forever.
        if log_stats or k in self._data:
            self._data.setdefault(k, []).append(v)

    def _log_scalar(self, k: str, v: float, step: int) -> None:
        if self._tb_logger is not None:
            self._tb_logger.add_scalar(k, v, step)
        if self._wandb_logger is not None:
            try:
                self._wandb_logger.log({k: v}, step=step)
            except Exception as e:
                print("[DataLogger] wandb scalar log: {}".format(e))

    def _log_stats(self, k: str, step: int) -> None:
        for stat_k, stat_v in self.get_stats(k).items():
            full_key = "{}-{}".format(k, stat_k)
            if self._tb_logger is not None:
                self._tb_logger.add_scalar(full_key, stat_v, step)
            if self._wandb_logger is not None:
                try:
                    self._wandb_logger.log({full_key: stat_v}, step=step)
                except Exception as e:
                    print("[DataLogger] wandb stats log: {}".format(e))

    def _log_image(self, k: str, v: np.ndarray, step: int) -> None:
        if v.ndim == 3:
            v = v[None, ...]
        if self._tb_logger is not None:
            self._tb_logger.add_images(k, img_tensor=v, global_step=step, dataformats="NHWC")
        if self._wandb_logger is not None:
            try:
                import wandb
                self._wandb_logger.log({k: wandb.Image(v)}, step=step)
            except Exception as e:
                print("[DataLogger] wandb image log: {}".format(e))

    # ---------- stats / lifecycle ----------

    def get_stats(self, k: str) -> dict[str, float]:
        arr = self._data[k]
        return {
            "mean": float(np.mean(arr)),
            "std":  float(np.std(arr)),
            "min":  float(np.min(arr)),
            "max":  float(np.max(arr)),
        }

    def close(self) -> None:
        if self._tb_logger is not None:
            self._tb_logger.close()
        if self._wandb_logger is not None:
            self._wandb_logger.finish()
