#!/usr/bin/env bash
# Auto-generated by env-generator (uv backend) — DO NOT HAND-EDIT.
# Re-run via `/nautilus:env-generator uv` to regenerate.
# Project: loco-mujoco    Python: 3.10
set -euo pipefail

cd "$(dirname "$0")/.."   # cd to repo root

# --- Step 1: prerequisites ---
command -v uv >/dev/null 2>&1 || { echo "[setup_uv] uv not found — install via 'curl -fsSL https://astral.sh/uv/install.sh | sh'" >&2; exit 1; }

# --- Step 2: create venv (idempotent) ---
if [ ! -d .venv ]; then
  uv venv --python 3.10 .venv
else
  echo "[setup_uv] .venv already exists; reusing"
fi

# Activate venv for the rest of this script.
# shellcheck disable=SC1091
source .venv/bin/activate

# --- Step 3: install steps (translated from nautilus/install_plan.json) ---
# (system apt) NOT executed — uv backend cannot sudo. Run manually if imports fail:
#     sudo apt install -y libegl1 libosmesa6 libgl1 libglib2.0-0
uv pip install -e .
uv pip install 'jax[cuda12]'

# --- Step 4: nautilus extras (logging + experiment tracking) ---
# These are NOT in the upstream install plan — they're injected by env-generator
# so the DataLogger (TensorBoard + W&B) used by rl-integration-generator works
# out-of-the-box. Idempotent: uv pip install skips already-installed packages.
uv pip install wandb tensorboardX

echo "[setup_uv] Done. Activate the venv with: source .venv/bin/activate"
